package tr.com.cetinkaya.data_repository.models.order_transaction

import tr.com.cetinkaya.common.enums.DataOrigin
import tr.com.cetinkaya.common.enums.SyncStatus
import tr.com.cetinkaya.domain.model.order_transaction.OrderTransactionDomainModel

data class OrderTransactionDataModel(
    val id: String,
    val orderDate: Long,
    val documentSeries: String,
    val documentNumber: Int,
    val rowNumber: Int,
    val stockId: String,
    val stockCode: String,
    val stockName: String,
    val barcode: String,
    val companyId: String,
    val currentCode: String,
    val companyName: String,
    val paymentPlanNumber: Int,
    val warehouseId: String,
    val warehouseNumber: Int,
    val warehouseName: String,
    val quantity: Double,
    val currencyType: Byte,
    val discount1: Double,
    val discount2: Double,
    val discount3: Double,
    val discount4: Double,
    val discount5: Double,
    val unitPrice: Double,
    val totalPrice: Double,
    val vatPointer: Byte,
    val currentResponsibilityCenter: String,
    val stockResponsibilityCenter: String,
    val remainingQuantity: Double,
    val deliveredQuantity: Double,
    val isColoredAndSized: Boolean,
    val syncStatus: SyncStatus,
    val dataOrigin: DataOrigin,
    val userCode: Int
)

fun OrderTransactionDataModel.toDomainModel(): OrderTransactionDomainModel = OrderTransactionDomainModel(
    id = this.id,
    orderDate = this.orderDate,
    documentSeries = this.documentSeries,
    documentNumber = this.documentNumber,
    rowNumber = this.rowNumber,
    stockId = this.stockId,
    stockCode = this.stockCode,
    stockName = this.stockName,
    barcode = this.barcode,
    companyId = this.companyId,
    companyCode = this.currentCode,
    companyName = this.companyName,
    paymentPlanNumber = this.paymentPlanNumber,
    warehouseId = this.warehouseId,
    warehouseNumber = this.warehouseNumber,
    warehouseName = this.warehouseName,
    quantity = this.quantity,
    currencyType = this.currencyType,
    discount1 = this.discount1,
    discount2 = this.discount2,
    discount3 = this.discount3,
    discount4 = this.discount4,
    discount5 = this.discount5,
    unitPrice = this.unitPrice,
    totalPrice = this.totalPrice,
    vatPointer = this.vatPointer,
    currentResponsibilityCenter = this.currentResponsibilityCenter,
    stockResponsibilityCenter = this.stockResponsibilityCenter,
    remainingQuantity = this.remainingQuantity,
    deliveredQuantity = this.deliveredQuantity,
    isColoredAndSized = this.isColoredAndSized,
    syncStatus = this.syncStatus,
    dataOrigin = this.dataOrigin,
    userCode = this.userCode
)
fun List<OrderTransactionDataModel>.toDomainModel(): List<OrderTransactionDomainModel> = this.map { it.toDomainModel() }

fun OrderTransactionDomainModel.toDataModel(): OrderTransactionDataModel = OrderTransactionDataModel(
    id = this.id,
    orderDate = this.orderDate,
    documentSeries = this.documentSeries,
    documentNumber = this.documentNumber,
    rowNumber = this.rowNumber,
    stockId = this.stockId,
    stockCode = this.stockCode,
    stockName = this.stockName,
    barcode = this.barcode,
    companyId = this.companyId,
    currentCode = this.companyCode,
    companyName = this.companyName,
    paymentPlanNumber = this.paymentPlanNumber,
    warehouseId = this.warehouseId,
    warehouseNumber = this.warehouseNumber,
    warehouseName = this.warehouseName,
    quantity = this.quantity,
    currencyType = this.currencyType,
    discount1 = this.discount1,
    discount2 = this.discount2,
    discount3 = this.discount3,
    discount4 = this.discount4,
    discount5 = this.discount5,
    totalPrice = this.totalPrice,
    unitPrice = this.unitPrice,
    vatPointer = this.vatPointer,
    currentResponsibilityCenter = this.currentResponsibilityCenter,
    stockResponsibilityCenter = this.stockResponsibilityCenter,
    remainingQuantity = this.remainingQuantity,
    deliveredQuantity = this.deliveredQuantity,
    isColoredAndSized = this.isColoredAndSized,
    syncStatus = this.syncStatus,
    dataOrigin = this.dataOrigin,
    userCode =  this.userCode
)