package tr.com.cetinkaya.domain.model.order_transaction

data class OrderTransactionDomainModel(
    val id: String,
    val orderDate: Long,
    val documentSeries: String,
    val documentNumber: Int,
    val rowNumber: Int,
    val stockId: String,
    val stockCode: String,
    val stockName: String,
    val barcode: String,
    val companyId: String,
    val companyCode: String,
    val companyName: String,
    val paymentPlanNumber: Int = 0,
    val warehouseId: String,
    val warehouseNumber: Int,
    val warehouseName: String,
    val quantity: Double,
    val unitPrice: Double,
    val currencyType: Byte,
    val discount1: Double,
    val discount2: Double,
    val discount3: Double,
    val discount4: Double,
    val discount5: Double,
    val totalPrice: Double,
    val vatPointer: Byte,
    val currentResponsibilityCenter: String,
    val stockResponsibilityCenter: String,
    val remainingQuantity: Double,
    val deliveredQuantity: Double,
    val isColoredAndSized: Boolean,
    val synchronizationStatus: String
)