package tr.com.cetinkaya.domain.model.order

data class OrderDomainModel (
    val id: String,
    val orderDate: String,
    val documentSeries: String,
    val documentNumber: Int,
    val lineNumber: Int,
    val stockCode: String,
    val currentCode: String,
    val quantity: Double,
    val inputWarehouseNumber: Int,
    val outputWarehouseNumber: Int,
    val salesman: String,
    val responsibilityCenter: String,
    val userCode: Int,
    val totalPrice: Double,
    val discount1: Double,
    val discount2: Double,
    val discount3: Double,
    val discount4: Double,
    val discount5: Double,
    val vatPointer: Byte,
    val orderId: String,
    val price: Double,
    val paperNumber: String,
    val companyNumber: Int,
    val storeNumber: Int,
    val barcode: String,
    val isColoredAndSized: Boolean
)