package tr.com.cetinkaya.data_local.db.entities

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.Index
import tr.com.cetinkaya.common.enums.DataOrigin
import tr.com.cetinkaya.common.enums.StockTransactionDocumentType
import tr.com.cetinkaya.common.enums.StockTransactionKind
import tr.com.cetinkaya.common.enums.StockTransactionType
import tr.com.cetinkaya.common.enums.SyncStatus
import tr.com.cetinkaya.data_repository.models.stock_transaction.StockTransactionDataModel
import java.util.Date
import java.util.UUID

@Entity(
    tableName = "stock_transactions", primaryKeys = ["id"],
    indices = [Index(value = ["transactionDocumentType", "documentSeries", "documentNumber", "lineNumber"], unique = true)],
)
data class StockTransactionEntity(
    val id: String,
    val transactionType: StockTransactionType,
    val transactionKind: StockTransactionKind,
    val isNormalOrReturn: Byte,
    val transactionDocumentType: StockTransactionDocumentType,
    val documentDate: Long,
    val documentSeries: String,
    val documentNumber: Int,
    val lineNumber: Long,
    val stockCode: String,
    val stockName: String,
    val companyCode: String,
    val quantity: Double,
    val inputWarehouseNumber: Int,
    val outputWarehouseNumber: Int,
    val paymentPlanNumber: Int,
    val salesman: String,
    val responsibilityCenter: String,
    val userCode: Int,
    val totalPrice: Double,
    val discount1: Double,
    val discount2: Double,
    val discount3: Double,
    val discount4: Double,
    val discount5: Double,
    val taxPointer: Byte,
    val orderId: String?,
    val price: Double,
    val paperNumber: String,
    val companyNumber: Int,
    val storeNumber: Int,
    val barcode: String,
    @ColumnInfo(defaultValue = "0") val isColoredAndSized: Boolean = false,
    val transportationStatus: Byte,
    @ColumnInfo(defaultValue = "(strftime('%s','now') * 1000)") val createdAt: Long = Date().time,
    @ColumnInfo(defaultValue = "(strftime('%s','now') * 1000)") val updatedAt: Long = Date().time,
    val syncStatus: SyncStatus,
    val dataOrigin: DataOrigin
) {
    companion object {
        fun create(
            transactionType: StockTransactionType,
            transactionKind: StockTransactionKind,
            isNormalOrReturn: Byte,
            documentType: StockTransactionDocumentType,
            documentDate: Long,
            documentSeries: String,
            documentNumber: Int,
            lineNumber: Long,
            stockCode: String,
            stockName: String,
            companyCode: String,
            quantity: Double,
            inputWarehouseNumber: Int,
            outputWarehouseNumber: Int,
            paymentPlanNumber: Int,
            salesman: String,
            responsibilityCenter: String,
            userCode: Int,
            totalPrice: Double,
            discount1: Double,
            discount2: Double,
            discount3: Double,
            discount4: Double,
            discount5: Double,
            taxPointer: Byte,
            orderId: String?,
            price: Double,
            paperNumber: String,
            companyNumber: Int,
            storeNumber: Int,
            barcode: String,
            isColoredAndSized: Boolean = false,
            transportationStatus: Byte,
            syncStatus: SyncStatus,
            dataOrigin: DataOrigin
        ) = StockTransactionEntity(
            id = UUID.randomUUID().toString(),
            transactionType = transactionType,
            transactionKind = transactionKind,
            isNormalOrReturn = isNormalOrReturn,
            transactionDocumentType = documentType,
            documentDate = documentDate,
            documentSeries = documentSeries,
            documentNumber = documentNumber,
            lineNumber = lineNumber,
            stockCode = stockCode,
            stockName = stockName,
            companyCode = companyCode,
            quantity = quantity,
            inputWarehouseNumber = inputWarehouseNumber,
            outputWarehouseNumber = outputWarehouseNumber,
            paymentPlanNumber = paymentPlanNumber,
            salesman = salesman,
            responsibilityCenter = responsibilityCenter,
            userCode = userCode,
            totalPrice = totalPrice,
            discount1 = discount1,
            discount2 = discount2,
            discount3 = discount3,
            discount4 = discount4,
            discount5 = discount5,
            taxPointer = taxPointer,
            orderId = orderId,
            price = price,
            paperNumber = paperNumber,
            companyNumber = companyNumber,
            storeNumber = storeNumber,
            barcode = barcode,
            isColoredAndSized = isColoredAndSized,
            transportationStatus = transportationStatus,
            syncStatus = syncStatus,
            dataOrigin = dataOrigin,
            createdAt = System.currentTimeMillis(),
            updatedAt = System.currentTimeMillis()
        )

    }
}

fun StockTransactionEntity.toProductDataModel(): StockTransactionDataModel {
    return StockTransactionDataModel(
        id = id,
        transactionType = transactionType,
        transactionKind = transactionKind,
        isNormalOrReturn = isNormalOrReturn,
        documentType = transactionDocumentType,
        documentDate = documentDate,
        documentSeries = documentSeries,
        documentNumber = documentNumber,
        lineNumber = lineNumber,
        stockCode = stockCode,
        stockName = stockName,
        companyCode = companyCode,
        quantity = quantity,
        inputWarehouseNumber = inputWarehouseNumber,
        outputWarehouseNumber = outputWarehouseNumber,
        paymentPlanNumber = paymentPlanNumber,
        salesman = salesman,
        responsibilityCenter = responsibilityCenter,
        userCode = userCode,
        totalPrice = totalPrice,
        discount1 = discount1,
        discount2 = discount2,
        discount3 = discount3,
        discount4 = discount4,
        discount5 = discount5,
        taxPointer = taxPointer,
        orderId = orderId,
        price = price,
        paperNumber = paperNumber,
        companyNumber = companyNumber,
        storeNumber = storeNumber,
        barcode = barcode,
        isColoredAndSized = isColoredAndSized,
        transportationStatus = transportationStatus,
        createdAt = createdAt,
        updatedAt = updatedAt,
        syncStatus = syncStatus,
        dataOrigin = dataOrigin
    )
}

fun StockTransactionDataModel.toEntity(): StockTransactionEntity {
    return StockTransactionEntity(
        id = id,
        transactionType = transactionType,
        transactionKind = transactionKind,
        isNormalOrReturn = isNormalOrReturn,
        transactionDocumentType = documentType,
        documentDate = documentDate,
        documentSeries = documentSeries,
        documentNumber = documentNumber,
        lineNumber = lineNumber,
        stockCode = stockCode,
        stockName = stockName,
        companyCode = companyCode,
        quantity = quantity,
        inputWarehouseNumber = inputWarehouseNumber,
        outputWarehouseNumber = outputWarehouseNumber,
        paymentPlanNumber = paymentPlanNumber,
        salesman = salesman,
        responsibilityCenter = responsibilityCenter,
        userCode = userCode,
        totalPrice = totalPrice,
        discount1 = discount1,
        discount2 = discount2,
        discount3 = discount3,
        discount4 = discount4,
        discount5 = discount5,
        taxPointer = taxPointer,
        orderId = orderId,
        price = price,
        paperNumber = paperNumber,
        companyNumber = companyNumber,
        storeNumber = storeNumber,
        barcode = barcode,
        isColoredAndSized = isColoredAndSized,
        transportationStatus = transportationStatus,
        syncStatus = syncStatus,
        dataOrigin = dataOrigin,
        createdAt = createdAt,
        updatedAt = updatedAt
    )
}

fun List<StockTransactionDataModel>.toEntity(): List<StockTransactionEntity> = this.map { it.toEntity() }
