package tr.com.cetinkaya.data_remote.models.barcode

import com.google.gson.annotations.SerializedName
import tr.com.cetinkaya.data_repository.models.barcode.GetBarcodeDefinitionByBarcodeDataModel

data class GetBarcodeDefinitionByBarcodeResponseModel(
    @SerializedName("id") val id: String,
    @SerializedName("barcode") val barcode: String,
    @SerializedName("stockId") val stockId: String,
    @SerializedName("stockCode") val stockCode: String,
    @SerializedName("stockName") val stockName: String,
    @SerializedName("stockMainGroupCode") val stockMainGroupCode: String,
    @SerializedName("stockMainGroupName") val stockMainGroupName: String,
    @SerializedName("stockSellerCurrentCode") val stockSellerCurrentCode: String,
    @SerializedName("stockSubgroupName") val stockSubgroupName: String,
    @SerializedName("stockRayonCode") val stockRayonCode: String,
    @SerializedName("stockRayonName") val stockRayonName: String,
    @SerializedName("price1") val price1: Double,
    @SerializedName("price2") val price2: Double,
    @SerializedName("price3") val price3: Double,
    @SerializedName("price4") val price4: Double,
    @SerializedName("price5") val price5: Double,
    @SerializedName("price6") val price6: Double,
    @SerializedName("price7") val price7: Double,
    @SerializedName("price8") val price8: Double,
    @SerializedName("price9") val price9: Double,
    @SerializedName("currencyType") val currencyType: Byte,
    @SerializedName("unit1Name") val unit1Name: String,
    @SerializedName("unit1Coefficient") val unit1Coefficient: Double,
    @SerializedName("unit1Weight") val unit1Weight: Double,
    @SerializedName("unit2Name") val unit2Name: String,
    @SerializedName("unit2Coefficient") val unit2Coefficient: Double,
    @SerializedName("unit2Weight") val unit2Weight: Double,
    @SerializedName("unit3Name") val unit3Name: String,
    @SerializedName("unit3Coefficient") val unit3Coefficient: Double,
    @SerializedName("unit3Weight") val unit3Weight: Double,
    @SerializedName("wholeSaleTax") val wholeSaleTax: Byte,
    @SerializedName("retailTax") val retailTax: Byte,
    @SerializedName("hasGoodsAcceptanceStopped") val hasGoodsAcceptanceStopped: Byte,
    @SerializedName("hasSaleStopped") val hasSaleStopped: Byte,
    @SerializedName("hasOrderStopped") val hasOrderStopped: Byte,
    @SerializedName("isColoredAndSized") val isColoredAndSized: Boolean
)

fun GetBarcodeDefinitionByBarcodeResponseModel.toDataModel() = GetBarcodeDefinitionByBarcodeDataModel(
    id = this.id,
    barcode = this.barcode,
    stockId = this.stockId,
    stockCode = this.stockCode,
    stockName = this.stockName,
    stockMainGroupCode = this.stockMainGroupCode,
    stockMainGroupName = this.stockMainGroupName,
    stockSellerCurrentCode = this.stockSellerCurrentCode,
    stockSubgroupName = this.stockSubgroupName,
    stockRayonCode = this.stockRayonCode,
    stockRayonName = this.stockRayonName,
    price1 = this.price1,
    price2 = this.price2,
    price3 = this.price3,
    price4 = this.price4,
    price5 = this.price5,
    price6 = this.price6,
    price7 = this.price7,
    price8 = this.price8,
    price9 = this.price9,
    currencyType = this.currencyType,
    unit1Name = this.unit1Name,
    unit1Coefficient = this.unit1Coefficient,
    unit1Weight = this.unit1Weight,
    unit2Name = this.unit2Name,
    unit2Coefficient = this.unit2Coefficient,
    unit2Weight = this.unit2Weight,
    unit3Name = this.unit3Name,
    unit3Coefficient = this.unit3Coefficient,
    unit3Weight = this.unit3Weight,
    wholeSaleTax = this.wholeSaleTax,
    retailTax = this.retailTax,
    hasGoodsAcceptanceStopped = this.hasGoodsAcceptanceStopped,
    hasSaleStopped = this.hasSaleStopped,
    hasOrderStopped = this.hasOrderStopped,
    isColoredAndSized = this.isColoredAndSized

)