package tr.com.cetinkaya.domain.model.barcode

data class GetBarcodeDefinitionByBarcodeDomainModel (
    val id: String,
    val barcode: String,
    val stockId: String,
    val stockCode: String,
    val stockName: String,
    val stockMainGroupCode: String,
    val stockMainGroupName: String,
    val stockSellerCurrentCode: String,
    val stockSubgroupName: String,
    val stockRayonCode: String,
    val stockRayonName: String,
    val price1: Double,
    val price2: Double,
    val price3: Double,
    val price4: Double,
    val price5: Double,
    val price6: Double,
    val price7: Double,
    val price8: Double,
    val price9: Double,
    val currencyType: Byte,
    val unit1Name: String,
    val unit1Coefficient: Double,
    val unit1Weight: Double,
    val unit2Name: String,
    val unit2Coefficient: Double,
    val unit2Weight: Double,
    val unit3Name: String,
    val unit3Coefficient: Double,
    val unit3Weight: Double,
    val wholeSaleTax: Byte,
    val retailTax: Byte,
    val hasGoodsAcceptanceStopped: Byte,
    val hasSaleStopped: Byte,
    val hasOrderStopped: Byte,
    val isColoredAndSized: Boolean
)