package tr.com.cetinkaya.data_repository.models.order

import tr.com.cetinkaya.domain.model.order.OrderDomainModel

data class OrderDataModel(
    val id: String,
    val orderDate: String,
    val documentSeries: String,
    val documentNumber: Int,
    val lineNumber: Int,
    val stockCode: String,
    val currentCode: String,
    val quantity: Double,
    val inputWarehouseNumber: Int,
    val outputWarehouseNumber: Int,
    val salesman: String,
    val responsibilityCenter: String,
    val userCode: Int,
    val totalPrice: Double,
    val discount1: Double,
    val discount2: Double,
    val discount3: Double,
    val discount4: Double,
    val discount5: Double,
    val vatPointer: Byte,
    val orderId: String,
    val price: Double,
    val paperNumber: String,
    val companyNumber: Int,
    val storeNumber: Int,
    val barcode: String,
    val isColoredAndSized: Boolean
)

fun OrderDataModel.toDomainModel(): OrderDomainModel = OrderDomainModel(
    id = this.id,
    orderDate = this.orderDate,
    documentSeries = this.documentSeries,
    documentNumber = this.documentNumber,
    lineNumber = this.lineNumber,
    stockCode = this.stockCode,
    currentCode = this.currentCode,
    quantity = this.quantity,
    inputWarehouseNumber = this.inputWarehouseNumber,
    outputWarehouseNumber = this.outputWarehouseNumber,
    salesman = this.salesman,
    responsibilityCenter = this.responsibilityCenter,
    userCode = this.userCode,
    totalPrice = this.totalPrice,
    discount1 = this.discount1,
    discount2 = this.discount2,
    discount3 = this.discount3,
    discount4 = this.discount4,
    discount5 = this.discount5,
    vatPointer = this.vatPointer,
    orderId = this.orderId,
    price = this.price,
    paperNumber = this.paperNumber,
    companyNumber = this.companyNumber,
    storeNumber = this.storeNumber,
    barcode = this.barcode,
    isColoredAndSized = this.isColoredAndSized
)

fun OrderDomainModel.toDataModel(): OrderDataModel = OrderDataModel(
    id = this.id,
    orderDate = this.orderDate,
    documentSeries = this.documentSeries,
    documentNumber = this.documentNumber,
    lineNumber = this.lineNumber,
    stockCode = this.stockCode,
    currentCode = this.currentCode,
    quantity = this.quantity,
    inputWarehouseNumber = this.inputWarehouseNumber,
    outputWarehouseNumber = this.outputWarehouseNumber,
    salesman = this.salesman,
    responsibilityCenter = this.responsibilityCenter,
    userCode = this.userCode,
    totalPrice = this.totalPrice,
    discount1 = this.discount1,
    discount2 = this.discount2,
    discount3 = this.discount3,
    discount4 = this.discount4,
    discount5 = this.discount5,
    vatPointer = this.vatPointer,
    orderId = this.orderId,
    price = this.price,
    paperNumber = this.paperNumber,
    companyNumber = this.companyNumber,
    storeNumber = this.storeNumber,
    barcode = this.barcode,
    isColoredAndSized = this.isColoredAndSized
)